name: Nuclio Debug
description: 'GitHub action to deploy model with nuclio container'
author: 'Didi Ruhyadi'
# original-author: 'William Justin'

branding:
  icon: 'box'  
  color: 'black'

outputs:
  status:
    description: "Container Status"
    value: ${{ steps.error.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Setup Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Get nuctl
      run: |
        curl -s https://api.github.com/repos/nuclio/nuclio/releases/tags/1.5.16 \
          | grep -i "browser_download_url.*nuctl.*$(uname)" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -O nuctl -qi - && chmod +x nuctl
      shell: bash

    - name: Create Project
      run: ./nuctl create project cvat
      shell: bash

    - name: Deploy Model
      run: |
        ./nuctl deploy --project-name cvat --path ./model \
          --volume ${pwd}/common:/opt/nuclio/common \
          --platform local
      shell: bash

    - name: Get Function
      run: ./nuctl get function
      shell: bash

    - name: Logging Model Container
      uses: jwalton/gh-docker-logs@v1
      with:
        dest: './logs'

    - name: Find Error
      id: error
      run: echo "::set-output name=status::$(python find_error.py --dir ./logs)"
      shell: bash

    - name: Print Output
      run: echo "${{ steps.error.outputs.status }}"
      shell: bash

    - name: Entrpoint
      run : |
        if [[  ${{ steps.error.outputs.status }} == 'failure' ]]
        then
            echo "[FAILURE] Can't load model"
            exit 1
        else
            echo "[SUCCESS] Model loaded"
        fi
      shell: bash